/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from 'next';
import Head from 'next/head';

import { api } from '~/utils/api';

const Home: NextPage = () => {
  const { mutateAsync: login } = api.example.auth.useMutation({
    async onSuccess() {
      // Get CSRF token
      const res = await fetch('/api/auth/csrf', {
        credentials: 'include'
      });
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      const data = await res.json();
      if (res.ok) {
        console.log(data);
      }
    }
  });

  const { data, error, isError } = api.example.superSecretAction.useQuery();

  const handleAuth = async () => {
    const res = await login();
    console.log(res);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <button onClick={() => handleAuth()}>Click to Auth</button>
          <h3>Super Secret Message</h3>
          {isError ? (
            <pre>{JSON.stringify(error.message)}</pre>
          ) : (
            <pre>{JSON.stringify(data)}</pre>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
